name: Analyse SonarCloud

on:
  push:
    branches:
      - '**'

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1
        with:
          organization: abdessalem-ghodbeni         # votre org SonarCloud
          projectKey:   abdessalem-ghodbeni
          token:         ${{ secrets.SONAR_TOKEN }}
